### ISSUE TITLE
此处有拼写错误， foldleft，应为 foldLeft

### ISSUE THREAD

**Issue by zhiweio** [ReactivePlatform/Pragmatic-Scala#29]
https://github.com/ReactivePlatform/Pragmatic-Scala/blob/30646181c8dd5d390906f168282e73211ce824f8/Introduction/FindMaxFunctional.sc#L2

**Comment by He-Pin** [comment]
@Zhiwei1996 Thanks a lot.

**Comment by He-Pin** [comment]
it's pretty ok on the sbt branch
https://github.com/ReactivePlatform/Pragmatic-Scala/blob/426538c87274bee1edf0b5ee6ea6125e68f7906e/src/main/scala/chapter1/FindMaxFunctional.scala#L22
