### ISSUE TITLE
此处有拼写错误，tolist 应为 toList

### ISSUE THREAD

**Issue by zhiweio** [ReactivePlatform/Pragmatic-Scala#30]
https://github.com/ReactivePlatform/Pragmatic-Scala/blob/c622bdd42af914d5248a445cab53865d6d236c1c/ProgrammingRecursions/Words.sc#L18

**Comment by zhiweio** [comment]
作者你好，很好奇你用的是 EMACS 之类编辑器还是IDE，我在看你翻译的书，大部分示例代码也都在jupyter 里运行测试了下
有个别大小写拼写错误，按理说有自动补全不会出现这些问题

**Comment by zhiweio** [comment]
https://github.com/ReactivePlatform/Pragmatic-Scala/blob/c622bdd42af914d5248a445cab53865d6d236c1c/ProgrammingRecursions/Words.sc#L24

这里的 `fromURl` ，应为 `fromURL`

**Comment by da-liii** [comment]
抱歉，我后面系统性检查一遍。其实我们的 sbt 分支是没有任何问题。

这边的代码我是从原书的samples导入的。

@Zhiwei1996

**Comment by zhiweio** [comment]
不是很清楚sbt 不同版本之间的差别
我用的 scala 2.12.6  sbt 1.1.6
这些拼写错误无伤大雅，我只是测试示例代码发现有 Bug 于是来这里反馈一下，可能其他读者如果也做同样的测试会产生困惑
另外有点不解的是，如果不同sbt 版本之间的函数名有这样的差别，命名不统一，会不会是个麻烦，就像 python3 和 python2 之间的标准库的命名
@sadhen

**Comment by da-liii** [comment]
非常感谢你的反馈。我这里说的sbt分支是 https://github.com/ReactivePlatform/Pragmatic-Scala/tree/sbt

这边错误是因为原来那本书提供的代码清单有错误，我会尽快修正。
