### ISSUE TITLE
惰性求值 在最坏的情况下 跟 严格求值 相比 性能差距在哪里，多做了哪些额外的工作？

### ISSUE THREAD

**Issue by ascjay** [ReactivePlatform/Pragmatic-Scala#54]

**Comment by da-liii** [comment]
具体的情况得具体分析。我建议你了解一下JMH。

可以从我的模版工程开始： https://zhuanlan.zhihu.com/p/44317356

**Comment by ascjay** [comment]
恩，好的我看看，多谢

**Comment by He-Pin** [comment]
@monkeyhyper 惰性求值主要是卡了一下，你可以从vavr的Lazy类看看。

**Comment by da-liii** [comment]
我已经推荐他看《Scala函数式编程》的第五章了。

**Comment by He-Pin** [comment]
你也还没睡啊。。。。
